version: '2.1'

services:
  handy:
    build: .
    network_mode: host
    privileged: true
    # Putting always here works for all instances _except_ the handover, because the handover strategy implementation changes this so the service won't restat
    # https://github.com/balena-os/balena-supervisor/blob/a89b23ac7c744befca46355245e9c7b51ed92861/src/compose/service-manager.ts#L633
    restart: always
    # ports:
    #   - "8085:8085"
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    labels:
      io.balena.update.strategy: hand-over
      io.balena.update.handover-timeout: 60000
    #   io.balena.features.dbus: '1'
    #   io.balena.features.kernel-modules: '1'
    #   io.balena.features.sysfs: '1'
    #   io.balena.features.supervisor-api: '1'
